# RedHat specific package installations
- include: RedHat.yml
  when: ansible_os_family  == "RedHat"

# Debian specific package installations
- include: Debian.yml
  when: ansible_os_family  == "Debian" or ansible_os_family == "Linuxmint"

# Gentoo specific package installations
- include: Gentoo.yml
  when: ansible_os_family  == "Gentoo"

- name: try to install packages required by get_url https and SNI if python is too old
  pip: name="{{ item }}"
  with_items:
    - urllib3
    - pyopenssl
    - ndg-httpsclient
    - pyasn1
  when: ansible_python_version|version_compare('2.7.9', '<')
  ignore_errors: true
